language: node_js
sudo: false
node_js:
    - 10
    - 9
    - 8
install: yarn
env:
  - WEBPACK_CONFIG="webpack.config.js"
  - WEBPACK_CONFIG="webpack.config.prod.js"
script:
  - yarn webpack --config=$WEBPACK_CONFIG